# 入门 #

 **导入pytorch包**

In [2]:
import torch

**创建一个行向量x，包含0到12的整数，它是默认创建整数，也可以指定创建浮点数，上面每个值被称为张量的元素，除非额外指定，否则张量存储到内存，并基于cpu计算**

In [6]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

**通过shape访问张量x（沿每个轴的长度）的形状**

In [4]:
x.shape

torch.Size([12])

**张量中元素个数，即形状的所有元素乘积，可以检查它大小**

In [6]:
x.numel()

12

**改变张量的形状，但是reshape不能改变它数量和元素值，注意，它可以改变张量的形状，但不会改变张量的大小，而且如果你故意整个大小不同的张量来运行会报错**

In [11]:
q=x.reshape(3,4)
q

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [14]:
b=x.reshape(4,4)
b

RuntimeError: shape '[4, 4]' is invalid for input of size 12

**可以不用手动来指定维度，比如如果我们目标形状为（高度，宽度），那么知道宽度，把高度搞为-1它就会自动计算出高度**

In [7]:
b=x.reshape(-1,4)
b

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

**创建全为0的张量**

In [13]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

**创建全为1的张量**

In [15]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

**创建随机数张量**

In [17]:
torch.randn(3,4)

tensor([[-0.2501, -0.4026, -0.3977,  0.3448],
        [ 0.9936,  0.5676, -0.1477,  1.7575],
        [-1.5782,  3.0201,  0.0659, -1.2529]])

**通过提供包含数值的python列表（或嵌套列表），来为所需张量中的每个元素赋予确定值。在这里，外层列表对应于轴0，内层列表对应于轴1**

In [19]:
torch.tensor([[2,1,3,4],[3,2,6,4],[9,7,5,4]])

tensor([[2, 1, 3, 4],
        [3, 2, 6, 4],
        [9, 7, 5, 4]])

# 运算符 #

**可以在同一形状的任意两个张量上执行按元素操作**

In [5]:
x=torch.tensor([1.0,2,4,8])
y=torch.tensor([2,2,2,2])
x+y,x-y,x*y,x/y,x**y  # **是求幂运算符

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

**求幂运算符，exp是对输入input逐元素进行以自然数e ee为底指数运算。**

In [7]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

**也可以多张张量拼接，端对端叠成更大张量，我们只需提供张量列表，以及沿哪个轴连接，dim就是设置沿哪个轴的参数**

In [21]:
x=torch.arange(12,dtype=torch.float32).reshape((3,4))
y=torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((x,y),dim=0),torch.cat((x,y),dim=1)# dim=0沿着y轴，dim=1沿着x轴

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

**如果要通过逻辑运算符构建二维张量，是每个位置都进行运算**

In [9]:
x==y #它是对每个位置今昔那个对应，如果一个位置上数一样，会显示true，反之会false

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

**对所有张量求和，它是所有元素相加**

In [11]:
x.sum()

tensor(66.)

# 广播机制 #

**广播机制是用来操作两张形状不同的张量来使他可以进行运算**
**工作方式：**
  （1）适当复制元素来扩展一到俩个数组，以便转换后，他们两个张量形状相同
  （2）对生产的数组执行按元素操作
   在大多数情况，我们将沿着数组中长度为1的轴进行广播，例子如下

In [3]:
a=torch.arange(3).reshape((3,1))
b=torch.arange(2).reshape((1,2))
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [4]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

因为a和b分别为3x1与1x2的矩阵，如果相加，因为形状不匹配，所以它会广播成为更大的3x2矩阵，原理是矩阵a复制列，b复制行，按元素相加

# 索引与切片 #

跟python数组一样，张量里面元素也是可以进行索引访问，第一个元素索引是0，最后一个索引是-1，可以指定范围来包含第一个和最后一个之前的元素

In [12]:
 q[0],q[-1],q[1:3]

(tensor([0, 1, 2, 3]),
 tensor([ 8,  9, 10, 11]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

除了读，我们还可以通过指定索引来写入元素

In [13]:
q[1,2]=9
q

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

如果想为多个元素赋予相同的值，只需要索引所有元素，然后为他们赋值即可

In [17]:
q[0:2, :]=12
q

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

# 节省内存 #

执行一些操作可能会导致为结果新分配内存。如，我们用Y=X+Y。我们可以将取消引用Y指向的张量，而是指向新分配被内存处的张量。

注：id()函数可返回对象的内存地址          

In [22]:
before=id(y)
y=y+x
id(y) == before

False

**这是不可取的，原因如下**

  （1）因为机器学习中参数很多，而且更新频率很快，所以最好不要进行不必要的内存分配，希望可以原地执行更新

  （2）如果不原地更新，其他引用还是会指向旧的内存位置，这样我们某些代码会无意中引用旧参数

解决办法有2个

（1）切片表示法：将操作的结果分配给先前分配的数组，如 Y[:]=<expression>.例子是通过创造一个z来比较俩内存，注： torch.zeros_like:生成和括号内变量维度维度一致的全是零的内容。
 （2）跟c语言缩写一个样

In [30]:
#方法1
#验证方法1
z=torch.zeros_like(y)
print(z)
print('id(z): ',id(z))
z[:]=x+y
print('id(z): ',id(z))
#验证方法2
before=id(y)
y[:]=y+x
id(y) == before

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
id(z):  1272596903120
id(z):  1272596903120


True

In [31]:
before=id(y)
y+=x
id(y) == before

True

# 转换成其他python对象 #

将框架定义的张量转换为numpy张量很简单，反之也很简单。torch张量和numpy张量会共享它们底层的内存，所以两个会同步修改

In [34]:
A=q.numpy()
B=torch.tensor(q)
type(A),type(B)

C:\Users\wxy\AppData\Local\Temp\ipykernel_22880\3580609473.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  B=torch.tensor(q)


(numpy.ndarray, torch.Tensor)

要将大小为1的张量转换为python标量，我们可以调用item函数以及python内置函数

In [35]:
a= torch.tensor([3.5])
a,a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)